INSERT INTO users(username, email, password) VALUES 
('user_1', 'user_1@test.com', '$2a$12$u2XeiM82ez0AGAKSjLSPcef0bHWFDh61oJ0xW8dG82RYAsnDPu0bO'),
('user_2', 'user_2@test.com', '$2a$12$mhdPYkSz5RwwFTyskw/gpuXbXn319FAQVVgJuPiFFvgK3F6SmKZaa');

INSERT INTO themes(titre, description) VALUES 
('Theme 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor felis in mattis sagittis. Morbi a dui at ex tincidunt blandit et eu diam. Ut massa felis, aliquet ac neque quis, accumsan vehicula nulla. Aliquam efficitur odio sit amet pretium accumsan. Pellentesque fermentum nulla ut nulla facilisis ornare in feugiat augue. Nam congue turpis vel cursus malesuada. Praesent in magna ligula. Sed posuere at odio eget pretium. Morbi sollicitudin posuere auctor. Aenean cursus posuere pretium. Nam dapibus fermentum sem, ultricies feugiat justo.'),
('Theme 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor felis in mattis sagittis. Morbi a dui at ex tincidunt blandit et eu diam. Ut massa felis, aliquet ac neque quis, accumsan vehicula nulla. Aliquam efficitur odio sit amet pretium accumsan. Pellentesque fermentum nulla ut nulla facilisis ornare in feugiat augue. Nam congue turpis vel cursus malesuada. Praesent in magna ligula. Sed posuere at odio eget pretium. Morbi sollicitudin posuere auctor. Aenean cursus posuere pretium. Nam dapibus fermentum sem, ultricies feugiat justo.');

INSERT INTO articles(titre, user_id, theme_id, date, texte) VALUES 
('Article 1', 1, 1, CURRENT_TIMESTAMP, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor felis in mattis sagittis. Morbi a dui at ex tincidunt blandit et eu diam. Ut massa felis, aliquet ac neque quis, accumsan vehicula nulla. Aliquam efficitur odio sit amet pretium accumsan. Pellentesque fermentum nulla ut nulla facilisis ornare in feugiat augue. Nam congue turpis vel cursus malesuada. Praesent in magna ligula. Sed posuere at odio eget pretium. Morbi sollicitudin posuere auctor. Aenean cursus posuere pretium. Nam dapibus fermentum sem, ultricies feugiat justo.'),
('Article 1', 2, 1, CURRENT_TIMESTAMP, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor felis in mattis sagittis. Morbi a dui at ex tincidunt blandit et eu diam. Ut massa felis, aliquet ac neque quis, accumsan vehicula nulla. Aliquam efficitur odio sit amet pretium accumsan. Pellentesque fermentum nulla ut nulla facilisis ornare in feugiat augue. Nam congue turpis vel cursus malesuada. Praesent in magna ligula. Sed posuere at odio eget pretium. Morbi sollicitudin posuere auctor. Aenean cursus posuere pretium. Nam dapibus fermentum sem, ultricies feugiat justo.'),
('Article 1', 1, 2, CURRENT_TIMESTAMP, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor felis in mattis sagittis. Morbi a dui at ex tincidunt blandit et eu diam. Ut massa felis, aliquet ac neque quis, accumsan vehicula nulla. Aliquam efficitur odio sit amet pretium accumsan. Pellentesque fermentum nulla ut nulla facilisis ornare in feugiat augue. Nam congue turpis vel cursus malesuada. Praesent in magna ligula. Sed posuere at odio eget pretium. Morbi sollicitudin posuere auctor. Aenean cursus posuere pretium. Nam dapibus fermentum sem, ultricies feugiat justo.');

INSERT INTO abonnements (user_id, theme_id) VALUES (2, 2);

INSERT INTO comments (comment, article_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 2, 1);